services:
  app-dev:
    build:
      context: .
      target: dev
    ports:
      - "8001:8000"
    environment:
      - DB_PATH=/app/db/dev-data.db
      - ENV=development
      - LOG_LEVEL=DEBUG
    volumes:
      - db-data:/app/db

  app-prod:
    build:
      context: .
      target: prod
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=/app/db/prod-data.db
      - ENV=production
      - LOG_LEVEL=WARNING
    volumes:
      - db-data:/app/db

volumes:
  db-data:
